let videoData=[
    "https://www.youtube.com/embed/Q4p8vRQX8uY?si=bh4sN3yvSVJmkfvc",
    "/2 Variables in JavaScript.mp4",
    "/3 const, let and var in JavaScript.mp4",
    "/4 Primitives and Objects in JavaScript.mp4",
    "/5 JavaScript Chapter 1-Practice Set.mp4",
    "/6 JavaScript Operators and Expressions.mp4",
    "/7 Conditional expressions in JavaScript.mp4",
    "/8 JavaScript Chapter 2 - Practice Set on Operators and Conditionals.mp4",
    "/9 For Loops in JavaScript.mp4",
    "/10 While Loops in JavaScript.mp4",
    "/11 Functions in JavaScript.mp4",
    "/12 JavaScript Chapter 3 - Practice Set on Loops and Functions.mp4",
    "/13 Introduction to Strings.mp4",
    "/14 JavaScript String Methods.mp4",
    "/15 JavaScript Chapter 4 - Practice Set on Strings.mp4",
    "/16 Introduction to Arrays.mp4",
    "/17 JavaScript Array Methods.mp4",
    "/18 Some More JavaScript Array Methods.mp4",
    "/19 Using Loops With Arrays in JavaScript.mp4",
    "/20 Map, Filter & Reduce in JavaScript.mp4",
]