let videoTitle=[
    "1. Introduction to JavaScript",
    "2. Variables in JavaScript",
    "3. const, let and var in JavaScript",
    "4. Primitives and Objects in JavaScript",
    "5. JavaScript Chapter-1: Practice Set",
    "6. JavaScript Operators and Expressions",
    "7. Conditional expressions in JavaScript",
    "8. JavaScript Chapter-2: Practice Set on Operators and Conditionals",
    "9. For Loops in JavaScript",
    "10. While Loops in JavaScript",
    "11. Functions in JavaScript",
    "12. JavaScript Chapter-3: Practice Set on Loops and Functions",
    "13. Introduction to Strings",
    "14. JavaScript String Methods",
    "15. JavaScript Chapter-4: Practice Set on Strings",
    "16. Introduction to Arrays",
    "17. JavaScript Array Methods",
    "18. Some More JavaScript Array Methods",
    "19. Using Loops With Arrays in JavaScript",
    "20. Map, Filter & Reduce in JavaScript",
    "21. JavaScript Chapter-5: Practice Set on Arrays",
    "22. Exercise-1: Guess the Number",
    "23. JavaScript in the Browser",
    "24. JavaScript Script Tag",
    "25. JavaScript Console Object",
    "26. Exercise-1: Solution & Shoutouts",
    "27. JavaScript alert, prompt & confirm",
    "28. DOM, BOM & Window Object",
    "29. JavaScript Chapter-6: Practice Set",
    "30. Exercise-2: Snake, Water and Gun",
    "31. Walking the DOM",
    "32. Accessing Children of an Element",
    "33. Parents & Siblings of an Element",
    "34. Element only Navigation",
    "35. Table Navigation",
    "36. Searching the DOM",
    "37. matches, closest and contains",
    "38. JavaScript Chapter-7: Practice Set",
    "39. Exercise-2: Snake, Water and Gun Solution & Shoutouts",
    "40. Exercise-3: Tell me a Joke",
    "41. innerHTML, outerHTML and other properties",
    "42. HTML Attributes and their methods",
    "43. HTML Insertion Methods",
    "44. insertAdjacentHTML, insertAdjacentElement and insertAdjacentText",
    "45. Changing HTML Classes using JavaScript_ className and classList",
    "46. setInterval and setTimeout in JavaScript",
    "47. Introduction to Browser Events",
    "48. Handling Browser Events",
    "49. JavaScript Chapter-8: Practice Set",
    "50. Exercise-3: Tell me a joke-Solution & Shoutouts",
    "51. Exercise-4: Clock using JavaScript",
    "52. Introduction to Callbacks",
    "53. Callback Hell & Pyramid of Doom",
    "54. Introduction to Promises",
    "55. Promise .then() and .catch()",
    "56. Promise Chaining .then() calls",
    "57. Attaching Multiple Handlers to a Promise",
    "58. The Promise API",
    "59. Async Await in JavaScript",
    "60. Error Handling try and catch",
    "61. The Error Object & Custom Errors",
    "62. The Finally Clause",
    "63. JavaScript Chapter-9: Practice Set",
    "64. Exercise-4: Clock Solutions & Shoutouts",
    "65. Exercise-5: Hackerman",
    "66. Fetch API",
    "67. Sending POST request with Fetch API",
    "68. Cookies in JavaScript",
    "69. Local Storage & related methods",
    "70. Session Storage & related methods",
    "71. JavaScript chapter-10 - Practice Set",
    "72. Exercise-5: Hackerman Solutions & Shoutouts",
    "73. Exercise-6: Todo List",
    "74. Introduction to Object Oriented Programming(OOPs)",
    "75. Protypes and proto in JavaScript",
    "76. Classes and Objects in JavaScript",
    "77. Constructors in JavaScript",
    "78. Inheritance & extends Keyword in JavaScript",
    "79. Constructors in JavaScript(Part-1)",
    "80. Constructors in JavaScript(Part-2)",
    "81. Static Method in JavaScript",
    "82. getters, setters & instance of Operator",
    "83. JavaScript Chapter-11: Practice Set",
    "84. Exercise-6: ToDo List Solution & Shoutouts",
    "85. Exercise-7: Password Generator",
    "86. IIFE - Immediately Invoked Function Expressions",
    "87. Destructuring assignment and Spread Operator",
    "88. local and global Scope in JavaScript",
    "89. Hoisting in JavaScript",
    "90. Closures in JavaScript",
    "91. Arrow Functions Revisited",
    "92. JavaScript Chapter-12: Practice Set",
    "93. Exercise-7: Password Generator Solution",
    "94. Exercise-8: Alarm clock",
    "95. JavaScript on the Server",
    "96. npm and Node.js Packages",
    "97. Modules in JavaScript",
    "98. Using Express.js to Create a Backend Server",
    "99. Regular Expressions in JavaScript",
    "100. Event Loop in JavaScript",
    "101. Exercise-8: Alarm clock Solutions and Shoutouts",
    "102. Project-1: PDF Merger WebApp Using JavaScript & Bootstrap",
    "103. Project-2: Bulk Rename Desktop App in Node.js",
]